<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="2" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="2889" started-at="2017-10-05T03:03:31Z" finished-at="2017-10-05T03:03:34Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="2889" started-at="2017-10-05T03:03:31Z" finished-at="2017-10-05T03:03:34Z">
      <class name="testrailtests.TestRailTests">
        <test-method status="FAIL" signature="failTest()[pri:0, instance:testrailtests.TestRailTests@53b32d7]" name="failTest" duration-ms="20" started-at="2017-10-05T14:03:31Z" finished-at="2017-10-05T14:03:31Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at org.testng.Assert.assertTrue(Assert.java:51)
	at testrailtests.TestRailTests.failTest(TestRailTests.java:32)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- failTest -->
        <test-method status="PASS" signature="testAPI()[pri:10, instance:testrailtests.TestRailTests@53b32d7]" name="testAPI" duration-ms="443" started-at="2017-10-05T14:03:33Z" finished-at="2017-10-05T14:03:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testAPI -->
        <test-method status="PASS" signature="passTest()[pri:20, instance:testrailtests.TestRailTests@53b32d7]" name="passTest" duration-ms="2" started-at="2017-10-05T14:03:34Z" finished-at="2017-10-05T14:03:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- passTest -->
      </class> <!-- testrailtests.TestRailTests -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
